services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: recipe-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@some.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"

volumes:
  postgres_data: